name: Python CI

on:
  push:
    branches:
      - main
      - dtree
      - kernelridge

  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          pip install pandas numpy scikit-learn

      - name: Run Decision Tree Model
        run: |
          python train.py

      - name: Run Kernel Ridge Model
        run: |
          python train2.py